### PR TITLE
Fix/blank identifier

### LINKED ISSUE #67: function with blank identifier
Given the following test code

```go
func TestCurryWithBlankIdentifier(t *testing.T) {
	f := func(a string, _ bool, c int) string {
		return fmt.Sprintf("%s%v%d", a, true, c)
	}
	curried := deriveCurryWithBlackIdentifier(f)
	want := `1atrue`
	got := curried("a")(false, 1)
	if got != want {
		t.Fatalf("got %s != want %s", got, want)
	}
}
```

`goderive` generates the following code

```go
// deriveCurryWithBlackIdentifier returns a function that has one parameter, which corresponds to the input functions first parameter, and a result that is a function, which takes the rest of the parameters as input and finally returns the original input function's results.
func deriveCurryWithBlackIdentifier(f func(a string, _ bool, c int) string) func(a string) func(_ bool, c int) string {
	return func(a string) func(_ bool, c int) string {
		return func(_ bool, c int) string {
			return f(a, _, c)
		}
	}
}
```

It has compilation error.

```
./derived.gen.go:4430:12: cannot use _ as value
``` 

I think these plugins have this issue.
- curry
- uncurry
- apply

### PR DESCRIPTION
**Pull request by jbl428**
Resolve #67 

Rename blank identifier to `prefix` + `position of parameter`.
Default prefix is `param_`.

Following plugins use rename function.

- apply
- curry
- flip
- toError
- uncurry

### CODE REVIEW

File: derive/params.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+	}
+	return false
+}
+
+func rename(tup *types.Tuple, prefix string) *types.Tuple {
+	vars := make([]*types.Var, tup.Len())
+	for i := range vars {
+		varValue := tup.At(i)
+		if varValue.Name() == blackIdentifier || strings.HasPrefix(varValue.Name(), prefix) {
+			varValue = types.NewVar(varValue.Pos(), varValue.Pkg(), prefix+strconv.Itoa(i), varValue.Type())
```
Comment (awalterschulze) [inline derive/params.go:53]: Nice and deterministic

File: derive/params.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+
+import (
+	"go/types"
+	"strconv"
+	"strings"
+)
+
+var blackIdentifier = "_"
+
+// RenameBlankIdentifier returns a signature that all black identified are renamed.
```
Comment (awalterschulze) [inline derive/params.go:25]: RenameBlankIdentifier returns a signature where all blank parameter names are renamed.

File: plugin/apply/apply.go [hunk 3]
```diff
@@ -47,10 +47,11 @@ type gen struct {
 }
 
 func (g *gen) Add(name string, typs []types.Type) (string, error) {
-	if _, _, err := g.parseTypes(name, typs); err != nil {
+	sig, _, err := g.parseTypes(name, typs)
+	if err != nil {
 		return "", err
 	}
-	return g.SetFuncName(name, typs...)
+	return g.SetFuncName(name, derive.RenameBlankIdentifier(sig), typs[1])
```
Comment (awalterschulze) [inline plugin/apply/apply.go:54]: Why not use last arg? as in
```go
sig, lastArg, err := g.parseTypes(name, typs)
...
return g.SetFuncName(name, derive.RenameBlankIdentifier(sig), lastArg)
```

File: derive/params.go [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+func RenameBlankIdentifier(sig *types.Signature, prefixs ...string) *types.Signature {
+	prefix := "param_"
+	if len(prefixs) > 0 {
```
Comment (awalterschulze) [inline derive/params.go:28]: Maybe it is ok to have two functions
```
RenameBlankIdentifier(sig *types.Signature)
```
and
```
RenameBlankIdentifierWith(sig *types.Signature, prefix string)
```

Simply because we do not support a list of prefixes and that why the type system makes it very clear
What do you think?

File: plugin/apply/apply.go [hunk 5]
```diff
@@ -74,8 +75,8 @@ func (g *gen) parseTypes(name string, typs []types.Type) (sig *types.Signature,
 
 func applySig(sig *types.Signature) (last *types.Var, returnFunc *types.Signature) {
 	vs := vars(sig.Params())
-	last = vs[len(vs) - 1]
-	second := types.NewTuple(vs[:len(vs) - 1]...)
+	last = vs[len(vs)-1]
```
Comment (awalterschulze) [inline plugin/apply/apply.go:78]: Been a while since I have done Go, is this gofmted?

File: plugin/uncurry/uncurry.go [hunk 6]
```diff
@@ -61,10 +61,15 @@ func (g *gen) Add(name string, typs []types.Type) (string, error) {
...
 		return "", fmt.Errorf("%s, expected 1 result for the input function", name)
 	}
-	if _, ok := sig.Results().At(0).Type().(*types.Signature); !ok {
+	retVar := sig.Results().At(0)
+	retSig, ok := retVar.Type().(*types.Signature)
+	if !ok {
 		return "", fmt.Errorf("%s, does not return a function", name)
 	}
-	return g.SetFuncName(name, sig)
+	retSig = derive.RenameBlankIdentifier(retSig, "innerParam_")
```
Comment (awalterschulze) [inline plugin/uncurry/uncurry.go:69]: Well done, this looks like it was complicated to figure out

File: test/normal/curry_test.go [hunk 7]
```diff
@@ -57,3 +57,15 @@ func TestCurryCurried(t *testing.T) {
 		t.Fatalf("got %s != want %s", got, want)
 	}
 }
+
+func TestCurryBlankIdentifier(t *testing.T) {
+	f := func(param_1 string, _ bool, param_0 int) string {
```
Comment (awalterschulze) [inline test/normal/curry_test.go:62]: Super great test, I love it

**Review by awalterschulze — COMMENTED** [review]
Only some nits
This looks great
Also, thank you so much for the tests

File: plugin/apply/apply.go (hunk 3 above)
Comment (jbl428) [reply plugin/apply/apply.go:54]: Yeah, I think we can use `lastArg` since `typs[1]` is used only for validation, not generating code.

File: derive/params.go (hunk 4 above)
Comment (jbl428) [reply derive/params.go:28]: Yes, you are right. I think It would be better to make type system clear.

File: plugin/apply/apply.go (hunk 5 above)
Comment (jbl428) [reply plugin/apply/apply.go:78]: Yes.

When I first create `apply.go`, the formatter of my IDE (Goland) was not `gofmt`. 
it uses their own formatter which is default.
I have found that later and I have change the setting to use `goimports` (superset of `gofmt`)

Comment (jbl428) [reply plugin/apply/apply.go:78]: Come to think of it, CI should have been failed when #65 PR was created.
I missed out on adding the `gofmt` step in CI. I will fix it.

Comment (awalterschulze) [reply plugin/apply/apply.go:78]: Yeah, I also suspected, easy oversight to make, fixing it would be great, thank you

Comment (awalterschulze) [reply plugin/apply/apply.go:78]: Seems CI is still passing, but the change persists?

Comment (jbl428) [reply plugin/apply/apply.go:78]: It is expected to pass since `apply.go` is now gofmted. 
If we roll back this PR except CI setting, It will fail.

Comment (awalterschulze) [reply plugin/apply/apply.go:78]: Aha okay great, my bad

**Review by awalterschulze — APPROVED** [review]
This looks great, thank you so much for such a well tested and elegant solution.
